server:
  port: 8080
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://db:3306/book?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update