server:
  port: 8080
  error:
    include-stacktrace: on_param

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:AZ
    username: sa
    password: password
    schema: classpath*:schema.sql

    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: create-drop