DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS BOOK;

CREATE TABLE IF NOT EXISTS USERS(
 ID INTEGER AUTO_INCREMENT PRIMARY KEY,
 AUTHHORITIES VARCHAR(255) NOT NULL,
 PASSWORD VARCHAR(255) NOT NULL,
 USERNAME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS BOOK (
 ID INTEGER AUTO_INCREMENT PRIMARY KEY,
 IDT_EPS INTEGER NOT NULL,
 AUTHOR VARCHAR(255) NOT NULL,
 CATEGOR VARCHAR(255) NOT NULL,
 TITLE VARCHAR(255) NOT NULL
);