name: Goiaba

on:
  push:
    branches: [ aula-api ]

jobs:
  laranja:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      gradlew: "./gradlew"

      steps:
        - uses: actions/checkout@v2

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew

        - uses: actions/checkout@v2
        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'

        - name: Run checkstyle
          run: |
            ${gradlew} check