# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  static-checking:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      gradlew: "./gradlew --console=plain -x test -x integrationTest --no-daemon"
      
    steps:
      - uses: actions/checkout@v2
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
    
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Run checkstyleMain
        run: |
          ${gradlew} checkstyleMain
        
      - name: Run checkstyleTest
        run: |
          ${gradlew} checkstyleTest
          
      - name: Run checkstyleIntegrationTest
        run: |
          ${gradlew} checkstyleIntegrationTest
          
  unit-tests:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      gradlew: "./gradlew --console=plain -x test -x integrationTest --no-daemon"
    needs: [ static-checking ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Unit Tests
        run: ${gradlew} test -x integrationTest
        
      - name: Mutation Test
        run: ${gradlew} pitest
    
        
  integration-tests:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      gradlew: "./gradlew --console=plain -x test -x integrationTest --no-daemon"
    needs: [ unit-tests ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Integration Tests
        run: ${gradlew} integrationTest
        
        
